import fs from 'node:fs/promises';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import { safeProjectPath, ensureParent } from './fs-safe.js';

export interface ProfileOptions { seconds?: number; intervalMs?: number; output?: string; }
export interface EditorPluginOptions { name?: string; outputDir?: string; toolbarText?: string; }
export interface NetTestOptions { mode?: 'enet'|'websocket'; host?: string; port?: number; timeoutMs?: number; }

function sh(cmd: string, args: string[], cwd: string, timeoutMs = 120000) {
  return new Promise<{code:number;stdout:string;stderr:string}>((resolve) => {
    const p = spawn(cmd, args, { cwd, stdio:['ignore','pipe','pipe'] });
    let stdout='', stderr=''; const timer=setTimeout(()=>{p.kill('SIGKILL'); resolve({code:124,stdout,stderr:stderr+'\nGJM timeout'});}, timeoutMs);
    p.stdout.on('data',d=>stdout+=d); p.stderr.on('data',d=>stderr+=d);
    p.on('close',code=>{clearTimeout(timer); resolve({code:code??1,stdout,stderr});});
  });
}

function q(v: unknown){ return JSON.stringify(String(v)); }

export async function generateEditorPlugin(root:string, opts:EditorPluginOptions={}) {
  const name = String(opts.name ?? 'GJMTools');
  const dir = String(opts.outputDir ?? 'addons/gjm_tools');
  const text = String(opts.toolbarText ?? 'GJM');
  const pluginCfg = `[plugin]\nname="${name}"\ndescription="Generated by Godot-J-MCP"\nauthor="GJM"\nversion="7.0.0"\nscript="res://${dir}/plugin.gd"\n`;
  const gd = `@tool\nextends EditorPlugin\n\nvar button: Button\n\nfunc _enter_tree():\n    button = Button.new()\n    button.text = ${q(text)}\n    button.tooltip_text = "Generated GJM editor action"\n    button.pressed.connect(_on_pressed)\n    add_control_to_container(CONTAINER_TOOLBAR, button)\n\nfunc _exit_tree():\n    if button:\n        remove_control_from_container(CONTAINER_TOOLBAR, button)\n        button.queue_free()\n\nfunc _on_pressed():\n    print("GJM_EDITOR_TOOL_CLICKED")\n`;
  await ensureParent(safeProjectPath(root, `${dir}/plugin.cfg`));
  await fs.writeFile(safeProjectPath(root, `${dir}/plugin.cfg`), pluginCfg);
  await fs.writeFile(safeProjectPath(root, `${dir}/plugin.gd`), gd);
  return {ok:true,name,directory:dir,files:[`${dir}/plugin.cfg`,`${dir}/plugin.gd`]};
}

export async function profileGame(root:string, godotBin:string, opts:ProfileOptions={}) {
  const seconds=Math.max(1,Math.min(300,Number(opts.seconds??10)));
  const out=String(opts.output??'.gjm_profile.json');
  const runnerRel='.gjm_tasks/profile-'+randomUUID()+'.gd';
  const runner=`extends SceneTree\n\nvar start_ms = 0\nfunc _initialize():\n    start_ms = Time.get_ticks_msec()\n    get_root().process_frame.connect(_sample)\n\nfunc _sample():\n    if Time.get_ticks_msec() - start_ms >= ${seconds*1000}:\n        var result = {"seconds": ${seconds}, "timestamp": Time.get_ticks_msec(), "fps": Engine.get_frames_per_second(), "node_count": _count(get_root()), "process_count": _process_count(get_root())}\n        var f = FileAccess.open(${q('res://'+out)}, FileAccess.WRITE)\n        if f: f.store_string(JSON.stringify(result)); f.close()\n        quit()\n\nfunc _count(n):\n    var c = 1\n    for x in n.get_children(): c += _count(x)\n    return c\n\nfunc _process_count(n):\n    var c = 0\n    if n.is_processing(): c += 1\n    for x in n.get_children(): c += _process_count(x)\n    return c\n`;
  await ensureParent(safeProjectPath(root, runnerRel));
  await fs.writeFile(safeProjectPath(root,runnerRel),runner);
  try{
    const r=await sh(godotBin,['--headless','--path',root,'--script',`res://${runnerRel}`],root,Math.max(15000,(seconds+10)*1000));
    let report:any=null; try{report=JSON.parse(await fs.readFile(safeProjectPath(root,out),'utf8'));}catch{}
    return {ok:r.code===0,code:r.code===0?'GJM-OK':'GJM-E307',exitCode:r.code,stdout:r.stdout,stderr:r.stderr,report,output:out};
  }finally{await fs.rm(safeProjectPath(root,runnerRel),{force:true}).catch(()=>{});}
}

export async function networkSmoke(root:string, godotBin:string, opts:NetTestOptions={}) {
  const mode=opts.mode??'enet'; const port=Number(opts.port??47831); const timeout=Number(opts.timeoutMs??20000);
  const rel='.gjm_tasks/network-smoke-'+randomUUID()+'.gd';
  const code = mode==='enet'
    ? `extends SceneTree\nfunc _initialize():\n    var p=NetworkedMultiplayerENet.new()\n    var err=p.create_server(${port},1)\n    if err != OK:\n        printerr("GJM_NETWORK_SERVER_ERROR ",err); quit(2); return\n    print("GJM_NETWORK_SERVER_READY")\n    get_tree().network_peer=p\n    await get_tree().create_timer(0.25).timeout\n    p.close_connection()\n    quit()\n`
    : `extends SceneTree\nfunc _initialize():\n    var s=WebSocketServer.new()\n    var err=s.listen(${port})\n    if err != OK:\n        printerr("GJM_NETWORK_SERVER_ERROR ",err); quit(2); return\n    print("GJM_NETWORK_SERVER_READY")\n    await get_tree().create_timer(0.25).timeout\n    s.stop()\n    quit()\n`;
  await ensureParent(safeProjectPath(root,rel)); await fs.writeFile(safeProjectPath(root,rel),code);
  try{const r=await sh(godotBin,['--path',root,'--script',`res://${rel}`],root,timeout); return {ok:r.code===0 && r.stdout.includes('GJM_NETWORK_SERVER_READY'),mode,port,exitCode:r.code,stdout:r.stdout,stderr:r.stderr};}
  finally{await fs.rm(safeProjectPath(root,rel),{force:true}).catch(()=>{});}
}
