import fs from 'node:fs/promises';
import { safeProjectPath, writeText } from './fs-safe.js';
import type { GodotMake, JsonValue, MakeNodeSpec, MakeSceneAction } from './types.js';

function q(value: string): string { return JSON.stringify(value); }

function gv(value: JsonValue): string {
  if (value === null) return 'null';
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  if (typeof value === 'number') return Number.isFinite(value) ? String(value) : 'null';
  if (typeof value === 'string') return q(value);
  if (Array.isArray(value)) return `[${value.map(gv).join(', ')}]`;
  return `{ ${Object.entries(value).map(([k, v]) => `${q(k)}: ${gv(v)}`).join(', ')} }`;
}

function collectResources(action: MakeSceneAction): Map<string, string> {
  const paths = new Set<string>();
  if (action.script) paths.add(action.script);
  if (action.root?.script) paths.add(action.root.script);
  for (const node of action.nodes ?? []) if (node.script) paths.add(node.script);
  const result = new Map<string, string>();
  let i = 1;
  for (const resource of paths) result.set(resource, `${i++}_script`);
  return result;
}

function emitNode(lines: string[], node: MakeNodeSpec, resources: Map<string, string>, godotMajor: number) {
  const parent = node.parent ?? '.';
  lines.push('', `[node name=${q(node.name)} type=${q(node.type)} parent=${q(parent)}]`);
  if (node.script) { const id = resources.get(node.script) ?? '1_script'; lines.push(`script = ${godotMajor >= 4 ? `ExtResource("${id}")` : `ExtResource(${id.replace(/\D/g, '') || '1'})`}`); }
  for (const [key, value] of Object.entries(node.properties ?? {})) lines.push(`${key} = ${gv(value)}`);
}

export function sceneText(action: MakeSceneAction, godotMajor = 4): string {
  const root = action.root ?? {};
  const rootName = root.name ?? 'Main';
  const rootType = root.type ?? 'Node';
  const nodes = action.nodes ?? [];
  const resources = collectResources(action);
  const lines: string[] = [];

  const format = godotMajor >= 4 ? 3 : 2;
  lines.push(`[gd_scene${resources.size ? ` load_steps=${resources.size + 1}` : ''} format=${format}]`);
  let rid = 1;
  for (const [resource, id] of resources) {
    void rid++;
    if (godotMajor >= 4) lines.push(`[ext_resource type="Script" path=${q(resource)} id=${q(id)}]`);
    else lines.push(`[ext_resource path=${q(resource)} type="Script" id=\"${id}\"]`);
  }
  lines.push('', `[node name=${q(rootName)} type=${q(rootType)}]`);
  const rootScript = root.script ?? action.script;
  if (rootScript) { const id = resources.get(rootScript) ?? '1_script'; lines.push(`script = ${godotMajor >= 4 ? `ExtResource("${id}")` : `ExtResource(${id.replace(/\D/g, '') || '1'})`}`); }
  for (const [key, value] of Object.entries(root.properties ?? {})) lines.push(`${key} = ${gv(value)}`);
  for (const node of nodes) emitNode(lines, node, resources, godotMajor);
  return `${lines.join('\n')}\n`;
}

function settingValue(value: JsonValue): string { return gv(value); }

async function ensureProjectFile(root: string, projectName?: string, godotMajor = 4) {
  const file = safeProjectPath(root, 'project.godot');
  try { await fs.access(file); return; } catch { /* create below */ }
  const name = projectName?.trim() || 'GJM Project';
  const initial = `; Engine configuration file.\n; Generated by Godot-J-MCP (GJM).\n\nconfig_version=${godotMajor >= 4 ? 5 : 4}\n\n[application]\nconfig/name=${q(name)}\n\n[display]\n\n`; 
  await fs.writeFile(file, initial, 'utf8');
}

async function mergeProjectSetting(root: string, section: string, key: string, value: JsonValue) {
  const file = safeProjectPath(root, 'project.godot');
  await ensureProjectFile(root);
  const text = await fs.readFile(file, 'utf8');
  const lines = text.split(/\r?\n/);
  const header = `[${section}]`;
  let start = lines.indexOf(header);
  if (start < 0) {
    while (lines.length && lines.at(-1) === '') lines.pop();
    if (lines.length) lines.push('');
    lines.push(header, `${key}=${settingValue(value)}`);
    await fs.writeFile(file, `${lines.join('\n')}\n`, 'utf8');
    return;
  }
  let end = lines.length;
  for (let i = start + 1; i < lines.length; i++) {
    if (/^\[[^\]]+\]$/.test(lines[i])) { end = i; break; }
  }
  const existing = lines.findIndex((line: string, i: number) => i > start && i < end && new RegExp(`^${key.replace(/[.*+?^${}()|[\\]\\]/g, '\\$&')}=`).test(line));
  if (existing >= 0) lines[existing] = `${key}=${settingValue(value)}`;
  else lines.splice(end, 0, `${key}=${settingValue(value)}`);
  await fs.writeFile(file, `${lines.join('\n')}\n`, 'utf8');
}

export async function applyMake(root: string, make: GodotMake, dryRun: boolean, godotMajor = 4) {
  const changes: Array<Record<string, unknown>> = [];
  if (!dryRun) await ensureProjectFile(root, make.project?.name ?? make.name, godotMajor);
  for (const action of make.actions) {
    switch (action.type) {
      case 'directory':
        safeProjectPath(root, action.path);
        changes.push({ type: action.type, path: action.path });
        if (!dryRun) await fs.mkdir(safeProjectPath(root, action.path), { recursive: true });
        break;
      case 'file':
      case 'script':
        safeProjectPath(root, action.path);
        changes.push({ type: action.type, path: action.path });
        if (!dryRun) await writeText(root, action.path, action.content);
        break;
      case 'scene':
        safeProjectPath(root, action.path);
        changes.push({ type: action.type, path: action.path, nodes: action.nodes?.length ?? 0 });
        if (!dryRun) await writeText(root, action.path, sceneText(action, godotMajor));
        break;
      case 'project_setting':
        safeProjectPath(root, 'project.godot');
        changes.push({ type: action.type, section: action.section, key: action.key });
        if (!dryRun) await mergeProjectSetting(root, action.section, action.key, action.value);
        break;
    }
  }
  return changes;
}
